### ISSUE TITLE
Obsidian 1.2.7 - colors are not applied

### ISSUE THREAD

**Issue by KillyMXI** [ecustic/obsidian-file-color#11]
Something have been changed with the recent update of Obsidian.

File color plugin is still shown in context menus and the color selection dialog remembers the color selected for a file/folder. But the color is not applied to file/folder names.

Error in the console:
![image](https://user-images.githubusercontent.com/13851064/235807958-5cbc2d95-5242-42a8-8f73-38782e6d1579.png)

Related issue with Icon Folder extension: https://github.com/FlorianWoelki/obsidian-icon-folder/issues/170

**Comment by WardF** [comment]
I came here to report the same issue; I'm also observing it and am happy to provide any additional info that may be useful.

**Comment by JimKnecht** [comment]
@ecustic I am having the same issue as Ward and Killy

**Comment by looneyapache** [comment]
Same issue :)

**Comment by Techno-wizard** [comment]
Same issue on a linux based system
```
app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'enabled')
    at get enabled [as enabled] (plugin:obsidian-icon-folder:3695:72)
    at eval (plugin:obsidian-icon-folder:3887:32)
    at Array.forEach (<anonymous>)
    at IconFolderPlugin.handleChangeLayout (plugin:obsidian-icon-folder:3886:38)
    at eval (plugin:obsidian-icon-folder:3797:82)
    at e.tryTrigger (app.js:1:957502)
    at e.trigger (app.js:1:957435)
    at t.trigger (app.js:1:1911307)
    at t.updateLayout (app.js:1:1903976)
    at r (app.js:1:1855474)
app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'enabled')
    at get enabled [as enabled] (plugin:obsidian-icon-folder:3695:72)
    at eval (plugin:obsidian-icon-folder:3887:32)
    at Array.forEach (<anonymous>)
    at IconFolderPlugin.handleChangeLayout (plugin:obsidian-icon-folder:3886:38)
    at eval (plugin:obsidian-icon-folder:3797:82)
    at e.tryTrigger (app.js:1:957502)
    at e.trigger (app.js:1:957435)
    at t.trigger (app.js:1:1911307)
    at t.updateLayout (app.js:1:1903976)
    at r (app.js:1:1855474)
plugin:obsidian-file-color:251 Uncaught TypeError: Cannot read properties of undefined (reading 'classList')
    at eval (plugin:obsidian-file-color:251:46)
    at Array.forEach (<anonymous>)
    at eval (plugin:obsidian-file-color:250:51)
    at Array.forEach (<anonymous>)
```

I see it is also affection file icons plugin

**Comment by DawsSauce97** [comment]
I am having the exact same problem. File colour community plugins were applied prior, and then wiped randomly. Appearance CSS Snippet codes work, as well as some other odd aesthetic community plug-ins.....just not the file colour modifying one.

**Comment by ecustic** [comment]
Hey everyone, thanks for reporting the issue! I’ll take a look at it as soon as possible. Hopefully that means before the end of the week.

**Comment by polyipseity** [comment]
If you edit `main.js` to replace the last two occurences of `titleEl` with `selfEl`, then the plugin will work normally. I have submitted #13 to fix it.

**Comment by JimKnecht** [comment]
Awesome, thank you @ecustic and @polyipseity this is one of my main don't want to go without plugins. I appreciate all the effort writing and maintaining it.
